### ISSUE TITLE
ksoftirqd/0 utilizes 100% CPU during portscan

### ISSUE THREAD

**Issue by MCLW777** [bmaeser/iptables-boilerplate#15]
Hello, I try to use it on Debian 9 for my LAMP and it works OK. Nevertheless, when I perform Nmap port scan from my PC, ksoftirqd/0 utilizes 100% of my server CPU for the scan time. As long as I have only 1 vcore on my VPS this makes whole server stuck for some time. Is there a way to improve it?

PS: I have disbaled "port scan" option in firewall, but it doesn't help.

**Comment by bmaeser** [comment]
imho this is not an iptables/firewall issue. when performing a portscan you send lots of requests to your server which causes lots of interrupt requests and the operating system cannot keep up finishing them, before the next one arrives. this especially is the case in virtual single core hosts.
1 vcpu normally only is one thread on a multicore cpu with hyperthreading.
try to run the same nmap portscan against the same kind of vm without any firewall activated, you will probably see the same results.

**Comment by MCLW777** [comment]
Thank you for the answer. I have tried performing Nmap scan without any firewall activated and it doesn't have any influence on system performance - CPU utilization for whole system during the scan is maximum 5%. As well I have tried scanning ports with my own firewall script activated (based on: http://wbitt.com/knowledge/how-to-tutorials/57-iptables-firewall-script-for-public-web-and-db-servers-.html) and it also doesn't charge CPU more than some percent.

**Comment by bmaeser** [comment]
i tried to reproduce this problem on single cpu-vhosts on ec2, digitalocean, linode and on a virtualbox vm on my dev-notebook. running stock debian9 minimal (64bit) and i cannot reproduce your problem. maybe you should do a fresh setup on a new vm, change your hosting provider or throw money at the problem and get a second cpu ;-)
