### ISSUE TITLE
Some questions and improvements

### ISSUE THREAD

**Issue by blaryjp** [bmaeser/iptables-boilerplate#6]
Hello, I've some questions:

1) Is this safe to put "EXTERNAL CONFIGS" section BEFORE all attacks detection rules ?

2) Regarding https://security.stackexchange.com/questions/4603/tips-for-a-secure-iptables-config-to-defend-from-attacks-client-side, I think that 2 rules are missing:
```BASH
## MAKE SURE NEW INCOMING TCP CONNECTIONS ARE SYN PACKETS
$IPTABLES -A INPUT -p tcp ! --syn -m state --state NEW -j DROP
## DROP PACKETS WITH INCOMING FRAGMENTS
$IPTABLES -A INPUT -f -j DROP
```

3) Why duplicate the invalid packets droping rules (Lines 68 and 146) ?

4) Why martians loging turned off by default ?

5) Can you add a "enable/disable ICMP" option ? Or, at least, add a "limit", to prevent a PING flood.

6) I don't need to restart a service (networking?) to apply sysctl settings, right ?

BTW, great boilerplate, very useful, thank you!

**Comment by gagomap** [comment]
@bmaeser : Can you update it for Ubuntu 16.04 ?

**Comment by bmaeser** [comment]
yes, its in my pipeline to port this project to systemd (among other things, like splitting it up into ipv4 and ipv6 settings). the problem is, i havent had much time lately and i guess it will be at least a couple more weeks till i get to it.

i suggest using ufw on ubuntu in the meantime.

**Comment by gagomap** [comment]
Thank you very much. I'm waiting for the next update :D
